INSERT INTO RESERVATIONS(ADDRESS, EMAIL, START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, PHONE_NUMBER, SURNAME, TABLE_NUMBER)
VALUES ('Marszałkowska 5', 'mpastuszka@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR, 2, CURRENT_TIMESTAMP), 5,  '+48 234 234 234', 'Pastuszka', 12);

INSERT INTO RESERVATIONS(ADDRESS, EMAIL, START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, PHONE_NUMBER, SURNAME, TABLE_NUMBER)
VALUES ('Marszałkowska 5', 'test@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR, 2, CURRENT_TIMESTAMP), 5,  '+48 567 567 567', 'Pastuszka', 6);

INSERT INTO RESERVATIONS(ADDRESS, EMAIL, START_BOOKING_TIME, END_BOOKING_TIME, NUMBER_OF_PEOPLE, PHONE_NUMBER, SURNAME, TABLE_NUMBER)
VALUES ('Marszałkowska 5', 'test2@gmail.com', CURRENT_TIMESTAMP, TIMESTAMPADD(HOUR, 2, CURRENT_TIMESTAMP), 5,  '+48 123 123 123', 'Pastuszka', 3);